(function() {
var notepad = null;
var translation_table = {};

window.addEventListener('load', function() {
    notepad = document.getElementById('notepad');
});

window.addEventListener('keydown', function(ev) {
    if (!ev.altKey && ev.ctrlKey && !ev.metaKey && ev.key == 'L') {  // Ctrl+Shift+L
        text = notepad.innerText;
        translation_table.forEach(e => {
            console.log(e);
            text = text.replace(new RegExp(e[0], 'ig'), e[1]);
        });
        notepad.innerText = text;
        ev.preventDefault();
    }
});

translation_table = [
    ['a', ''],
    ['akesi', ''],
    ['ala', ''],
    ['alasa', ''],
    ['ali', ''],
    ['ale', ''],
    ['anpa', ''],
    ['ante', ''],
    ['anu', ''],
    ['awen', ''],
    ['e', ''],
    ['en', ''],
    ['esun', ''],
    ['ijo', ''],
    ['ike', ''],
    ['ilo', ''],
    ['insa', ''],
    ['jaki', ''],
    ['jan', ''],
    ['jelo', ''],
    ['jo', ''],
    ['kala', ''],
    ['kalama', ''],
    ['kama', ''],
    ['kasi', ''],
    ['ken', ''],
    ['kepeken', ''],
    ['kili', ''],
    ['kiwen', ''],
    ['ko', ''],
    ['kon', ''],
    ['kule', ''],
    ['kulupu', ''],
    ['kute', ''],
    ['la', ''],
    ['lape', ''],
    ['laso', ''],
    ['lawa', ''],
    ['len', ''],
    ['lete', ''],
    ['li', ''],
    ['lili', ''],
    ['linja', ''],
    ['lipu', ''],
    ['loje', ''],
    ['lon', ''],
    ['luka', ''],
    ['lukin', ''],
    ['lupa', ''],
    ['ma', ''],
    ['mama', ''],
    ['mani', ''],
    ['meli', ''],
    ['mi', ''],
    ['mije', ''],
    ['moku', ''],
    ['moli', ''],
    ['monsi', ''],
    ['mu', ''],
    ['mun', ''],
    ['musi', ''],
    ['mute', ''],
    ['nanpa', ''],
    ['nasa', ''],
    ['nasin', ''],
    ['nena', ''],
    ['ni', ''],
    ['nimi', ''],
    ['noka', ''],
    ['o', ''],
    ['olin', ''],
    ['ona', ''],
    ['open', ''],
    ['pakala', ''],
    ['pali', ''],
    ['palisa', ''],
    ['pan', ''],
    ['pana', ''],
    ['pi', ''],
    ['pilin', ''],
    ['pimeja', ''],
    ['pini', ''],
    ['pipi', ''],
    ['poka', ''],
    ['poki', ''],
    ['pona', ''],
    ['sama', ''],
    ['seli', ''],
    ['selo', ''],
    ['seme', ''],
    ['sewi', ''],
    ['sijelo', ''],
    ['sike', ''],
    ['sin', ''],
    ['sina', ''],
    ['sinin', ''],
    ['sitelen', ''],
    ['sona', ''],
    ['soweli', ''],
    ['suli', ''],
    ['suno', ''],
    ['supa', ''],
    ['suwi', ''],
    ['tan', ''],
    ['taso', ''],
    ['tawa', ''],
    ['telo', ''],
    ['tenpo', ''],
    ['toki', ''],
    ['tomo', ''],
    ['tu', ''],
    ['unpa', ''],
    ['uta', ''],
    ['utala', ''],
    ['walo', ''],
    ['wan', ''],
    ['waso', ''],
    ['wawa', ''],
    ['weka', ''],
    ['wile', ''],
    ['kin', ''],
    ['namako', ''],
    ['oko', ''],
    ['\\.', ''],
    [',', ''],
    [':', ''],
    ['!', ''],
    ['\\?', ''],
    ['-', '―'],
    [' ', ''],
].sort((a, b) => b[0].length - a[0].length);
console.log(translation_table);
})();
/*
*/